-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "dateId" TEXT,
ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AddForeignKey
ALTER TABLE "Event" ADD FOREIGN KEY ("dateId") REFERENCES "Calendar"("day_id") ON DELETE SET NULL ON UPDATE CASCADE;
